#!/bin/sh

# Installs package to /opt/epsonFiscalDriver and service unit

set -e

if [ $(id -u) -ne 0 ]; then
    echo "ERROR: superuser required for this install" >&2
    exit 10
fi

PACKAGE=epsonFiscalDriver

umask 0022

rm -fr "/opt/${PACKAGE}"
cp -rp ${PACKAGE} /opt

cp /opt/${PACKAGE}/${PACKAGE}@.service /lib/systemd/system || {
    echo "ERROR: failed to install systemd unit. You can install it manually from /opt/${PACKAGE}" >&2
}

mkdir -p /etc/${PACKAGE}.d

if ! [ -f /etc/${PACKAGE}.d/default.conf ]; then
    cp /opt/${PACKAGE}/default.conf /etc/${PACKAGE}.d
fi

cp /opt/${PACKAGE}/restartAllFiscalDrivers.desktop /usr/share/applications/
update-desktop-database || echo "Falló la actualización de desktop database"

systemctl daemon-reload

systemctl enable epsonFiscalDriver@default.service
